### ISSUE TITLE
Create / produce additional GOlr fields to support default relation change

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#624]
There are fields in GOlr, like `regulates_transitivity_graph_json`, which seem to have been created after the initial switch from isa_partof to regulates and have no isa_partof analog. The schema will have to be extended and those would need to be added to the loader.

This is a spinoff from #620

**Comment by kltm** [comment]
Explicit metadata "regulates" fields:
regulates_closure
regulates_closure_label
regulates_transitivity_graph_json

The last one is the problematic one. It is defined in only: neo-config.yaml and ont-config.yaml

**Comment by kltm** [comment]
As a technical "huh" note, given how we do this, we could be done this in the (relative) snap of the fingers if we forgive ourselves the field id "regulates_..." and just redefine it using the relation set we want.
```yaml
  - id: regulates_transitivity_graph_json
    description: "JSON blob form of the local relation transitivity graph. Uses various relations (including regulates, occurs in, capable_of)."
    display_name: Regulates transitivity graph (JSON)
    type: string
    property:
      - "getLineageShuntGraphJSON"
      - "BFO:0000050"
      - "BFO:0000066"
      - "RO:0002211"
      - "RO:0002212"
      - "RO:0002213"
      - "RO:0002215"
      - "RO:0002216"
    indexed: false
```
